name: Azure CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login with Azure Service Principal
      run: |
        az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }}} --tenant ${{ secrets.AZURE_TENANT_ID }} --password ${{ secrets.AZURE_CLIENT_PASSWORD }}

    - name: Login To Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Docker Build and Push
      run: |  
        docker build -t ${{ secrets.ACR_REGISTRY }}/coop-de-grace:latest .
        docker push ${{ secrets.ACR_REGISTRY }}/coop-de-grace:latest
